name: Test-Workflow
on: workflow_dispatch
jobs:
  First_job:
    runs-on: ubuntu-latest
    steps:
      - name: This is steps task
        run: echo "This is first Steps"
  secod_job:
    runs-on: ubuntu-latest
    steps:
      - name: This is steps task
        run: echo "Good By"
